// Code generated by goctl. DO NOT EDIT!
// Source: task.proto

package server

import (
	"context"

	"backend/service/im/cmd/rpc/internal/logic"
	"backend/service/im/cmd/rpc/internal/svc"
	"backend/service/im/cmd/rpc/pb"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

// 返送单条消息
func (s *TaskServer) PushSingleToConnect(ctx context.Context, in *pb.TaskSend) (*pb.TaskSuccessReply, error) {
	l := logic.NewPushSingleToConnectLogic(ctx, s.svcCtx)
	return l.PushSingleToConnect(in)
}
