FROM node:12.16.1

WORKDIR /webroot/
COPY . .

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN rm -rf node_modules
RUN rm -rf package-lock.json
RUN cnpm install || npm install
RUN npm run build

FROM nginx:alpine
LABEL MAINTAINER=""


COPY --from=0 /webroot/dist /usr/share/nginx/html
