// Code generated by goctl. DO NOT EDIT.
package types

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminUpdatePwdReq struct {
	OldPassword string `json:"oldPassword"`
	Password    string `json:"password"`
}

type AdminPostReq struct {
	Avatar      string `db:"avatar" json:"avatar,default="`                            // 头像地址
	CreateBy    string `db:"create_by" json:"create_by,default="`                      // 创建者
	DelFlag     int64  `db:"del_flag" json:"del_flag,default=0"`                       // 删除标志（0代表存在 2代表删除）
	DeptId      int64  `db:"dept_id" json:"dept_id,default=0"`                         // 部门ID
	Email       string `db:"email" json:"email,default="`                              // 用户邮箱
	Id          int64  `db:"id" json:"id,optional"`                                    // 用户ID
	LoginDate   string `db:"login_date" json:"login_date,default=2006-01-02 15:04:05"` // 最后登录时间
	LoginIp     string `db:"login_ip" json:"login_ip,default="`                        // 最后登录IP
	NickName    string `db:"nick_name" json:"nick_name,optional"`                      // 用户昵称
	Password    string `db:"password" json:"password,default="`                        // 密码
	Phonenumber string `db:"phonenumber" json:"phonenumber,default="`                  // 手机号码
	Remark      string `db:"remark" json:"remark,default=Empty string"`                // 备注
	RoleId      int64  `db:"role_id" json:"role_id,default=0"`                         // 角色ID
	Sex         int64  `db:"sex" json:"sex,default=0"`                                 // 用户性别（0男 1女 2未知）
	Status      int64  `db:"status" json:"status,default=0"`                           // 帐号状态（0正常 1停用）
	UpdateBy    string `db:"update_by" json:"update_by,default="`                      // 更新者
	UserName    string `db:"user_name" json:"user_name,optional"`                      // 用户账号
	UserType    int64  `db:"user_type" json:"user_type,default=0"`                     // 用户类型（0系统用户）
}

type AdminReply struct {
	Id       int64  `json:"id"`
	UserName string `json:"user_name"`
}

type AdminListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type AdminDelReq struct {
	Id int64 `json:"id"`
}

type AdminDelBatchReq struct {
	Ids string `json:"ids"`
}

type AdminChangeAvatarReq struct {
	Id int64 `json:"id,optional" form:"id,optional"`
}

type MenuPostReq struct {
	Icon      string `db:"icon" json:"icon,optional"`                     // 附加属性
	Path      string `db:"path" json:"path,optional"`                     // 路由path
	Hidden    int64  `db:"hidden" json:"hidden,optional"`                 // 1是0否在列表隐藏
	ParentId  int64  `db:"parent_id" json:"parent_id,optional,default=0"` // 父菜单ID
	Name      string `db:"name" json:"name,optional"`                     // 路由name
	Component string `db:"component" json:"component,optional"`           // 对应前端vue文件路径
	Sort      int64  `db:"sort" json:"sort,optionalt,default=0"`          // 排序标记
	Title     string `db:"title" json:"title,optional"`                   // 附加属性
	Id        int64  `db:"id" json:"id,optional,default=0"`               // ID
}

type MenuReply struct {
	Id       int64  `json:"id"`
	UserName string `json:"user_name"`
}

type MenuListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type MenuDelReq struct {
	Id int64 `json:"id"`
}

type MenuDelBatchReq struct {
	Ids string `json:"ids"`
}

type SystemApiPostReq struct {
	ApiGroup    string `db:"api_group" json:"api_group,optional"`     // api组
	Description string `db:"description" json:"description,optional"` // api中文描述
	Id          int64  `db:"id" json:"id,optional"`                   //
	Method      string `db:"method" json:"method,default=POST"`       // 请求方法
	Path        string `db:"path" json:"path,optional"`               // api路径
}

type SystemApiReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SystemApiListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type SystemApiDelReq struct {
	Id int64 `json:"id"`
}

type SystemApiDelBatchReq struct {
	Ids string `json:"ids"`
}

type SystemRolePostReq struct {
	Id       int64  `db:"id" json:"id,optional"`                //
	Name     string `db:"name" json:"name,optional"`            // 角色名
	ParentId int64  `db:"parent_id" json:"parent_id,default=0"` // 父级ID
	Sort     int64  `db:"sort" json:"sort,default=0"`           // 排序
}

type SystemRoleReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SystemRoleListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type SystemRoleDelReq struct {
	Id int64 `json:"id"`
}

type SystemRoleDelBatchReq struct {
	Ids string `json:"ids"`
}

type SystemDepartmentPostReq struct {
	Ancestors string `db:"ancestors" json:"ancestors,default="`  // 祖级列表
	CreateBy  string `db:"create_by" json:"create_by,default="`  // 创建者
	Email     string `db:"email" json:"email,default="`          // 邮箱
	Id        int64  `db:"id" json:"id,optional"`                //
	Leader    string `db:"leader" json:"leader,default="`        // 负责人
	Name      string `db:"name" json:"name,default="`            // 部门名称
	ParentId  int64  `db:"parent_id" json:"parent_id,default=0"` // 父级ID
	Phone     string `db:"phone" json:"phone,default="`          // 联系电话
	Sort      int64  `db:"sort" json:"sort,default=0"`           // 排序
	Status    int64  `db:"status" json:"status,default=0"`       // 部门状态（0正常 1停用）
	UpdateBy  string `db:"update_by" json:"update_by,default="`  // 更新者
}

type SystemDepartmentReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SystemDepartmentListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type SystemDepartmentDelReq struct {
	Id int64 `json:"id"`
}

type SystemDepartmentDelBatchReq struct {
	Ids string `json:"ids"`
}

type SystemRoleMenuPostReq struct {
	Id     int64 `db:"id" json:"id,optional"`            //
	MenuId int64 `db:"menu_id" json:"menu_id,default=0"` // 菜单ID
	RoleId int64 `db:"role_id" json:"role_id,default=0"` // 角色ID
}

type SystemRoleMenuReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SystemRoleMenuListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type SystemRoleMenuDelReq struct {
	Id int64 `json:"id"`
}

type SystemRoleMenuDelBatchReq struct {
	Ids string `json:"ids"`
}

type SystemRoleMenuAddReq struct {
	MenuIds string `json:"menu_ids"`
	RoleId  int64  `json:"role_id"`
}

type SystemRoleApiPostReq struct {
	PType string `db:"p_type" json:"p_type,default="` //
	V0    string `db:"v0" json:"v0,default="`         //
	V1    string `db:"v1" json:"v1,default="`         //
	V2    string `db:"v2" json:"v2,default="`         //
	V3    string `db:"v3" json:"v3,default="`         //
	V4    string `db:"v4" json:"v4,default="`         //
	V5    string `db:"v5" json:"v5,default="`         //
}

type RoleApisReq struct {
	SystemRoleApiPostReqs []SystemRoleApiPostReq `json:"role_apis"`
	RoleId                int64                  `json:"role_id"`
}

type SystemRoleApiReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SystemRoleApiListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type SystemRoleApiDelReq struct {
	Id int64 `json:"id"`
}

type SystemRoleApiDelBatchReq struct {
	Ids string `json:"ids"`
}
