<?php

use Illuminate\Database\Seeder;

class ShopGoodsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shop_goods')->delete();
        
        \DB::table('shop_goods')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 2,
                'goods_sn' => '12121',
                'goods_name' => '全站设计样例-简洁电商',
                'brand_id' => 4,
                'goods_number' => 102,
                'keywords' => '从产品设计、界面设计到功能开发的代码编写，全部由小T技术团队完成',
                'goods_brief' => '从产品设计、界面设计到功能开发的代码编写，全部由小T技术团队完成',
                'goods_desc' => '<p></p><p><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/152966823553489623.jpg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/1529668235379550341.jpg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/1529668235372901734.jpg-_600" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 100,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '8000.00',
                'freight_price' => '0.00',
                'extra_price' => '2000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/cca06d0bb04b32409e6ac2fa56f9d274.png',
                'list_pic_url' => '["images\\/d63f58ba8e1c9a00bf098ab32e0329fc.jpg","images\\/09230cd1b817e3ac12119ab1f90184c5.jpg","images\\/2ff74fc85e18b477aeef9cb1915646c9.jpg"]',
                'retail_price' => '10000.00',
                'sell_volume' => 9,
                'primary_product_id' => 0,
                'unit_price' => '10000.00',
                'promotion_desc' => '限时折扣',
                'promotion_tag' => '限时折扣',
                'vip_exclusive_price' => '121.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 1,
                'is_hot' => 0,
                'created_at' => NULL,
                'updated_at' => '2018-06-23 09:51:07',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 2,
                'goods_sn' => '',
                'goods_name' => '智能硬件系统',
                'brand_id' => 4,
                'goods_number' => 11,
                'keywords' => '智能硬件项目，专门针对小型智能硬件厂商提供OEM和ODM服务',
                'goods_brief' => '智能硬件项目，专门针对小型智能硬件厂商提供OEM和ODM服务',
                'goods_desc' => '<p></p><p></p><p></p><p><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/H8rrjuIe8jSx8siHN2nLCo9tczNYZVzNW3N3EX7e.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/SBBb5QItC9HQKCL9FQKKKqroaIe9hftaYo9XTtrn.jpeg" style="max-width:100%;"><br></p><p><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/jq319PEDZvvur05mW49HJeXsC7tA2XC36gF0Fco4.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/9sZ8ofbLL8AFuUn2sLgqm8mW3VnVlQXWUkcZgqIw.jpeg" style="max-width:100%;"><br></p><p><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/NAxb6gT3fGqEhF4xMSa4Rr1kpsonV7JgB7luu1yQ.jpeg" style="max-width:100%;"><br></p><p><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/3gBK2FdWOPjwg2yX22DvnhADpz3dGuWrFsgwh4Wr.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/XQzN3MWIU0W3xgreQoak2eWqV5C0VpXZwCK7ZXNw.jpeg" style="max-width:100%;"><br></p><p><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '12000.00',
                'freight_price' => '0.00',
                'extra_price' => '3000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/d1ba64334a79e45a2c7c61a2805efefa.png',
                'list_pic_url' => '["images\\/1d50355df1589db671bcfedd813939e5.jpg","images\\/99c85b546472d075b31e678b0483de62.jpg","images\\/01e1636376384e56ca7e84027d2d93e3.jpg","images\\/ca75f5dbb626114d6bf064e5997fcb05.jpg","images\\/00d8e2d61852480e35ffb3d730833a8e.jpg"]',
                'retail_price' => '15000.00',
                'sell_volume' => 9,
                'primary_product_id' => 0,
                'unit_price' => '15000.00',
                'promotion_desc' => '暂无优惠',
                'promotion_tag' => '暂无优惠',
                'vip_exclusive_price' => '11111.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 1,
                'created_at' => '2018-06-05 09:37:01',
                'updated_at' => '2018-06-23 09:41:09',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 5,
                'goods_sn' => '',
                'goods_name' => '越南进口红心火龙果 3个装 大果',
                'brand_id' => 4,
                'goods_number' => 2,
                'keywords' => '果肉更足，享受饱满的甜蜜诱惑！红果富含花青素，天然抗氧化营养库！',
                'goods_brief' => '【越南直采 精选大果】果肉更足，享受饱满的甜蜜诱惑！红果富含花青素，天然抗氧化营养库！',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/WAEaibm1sKNXDSYrfDswiQzeqf9aowzTffSEb5Y6.jpeg" style="max-width:100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/kOPvWdE3g5xQdO0kvqHuneqxxXRhWng7AZlHUA31.jpeg" style="max-width: 100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/3Nxm8ifRAT08fAPmzGHgtjOOP7coQxKgT68pMKpi.jpeg" style="max-width: 100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/ZR8iMRFjGRCC161LbwrmdVyapRmpBHlTP8QV8X0T.jpeg" style="max-width: 100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/ZepaMrCU3aDRzg6B7kbGpExPpspTWJ51KtbERjdI.jpeg" style="max-width: 100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/H7SDQFOAyOsZ8cKiy2og2fwtC9uIsXT0QoMV1XGt.jpeg" style="max-width: 100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '44.00',
                'freight_price' => '0.00',
                'extra_price' => '44.00',
                'is_new' => 0,
                'goods_unit' => '',
                'primary_pic_url' => 'images/a204d50e68dea8f2797b0ea29dc0bc2d.jpg',
                'list_pic_url' => '["images\\/b46d3c10ec815cf5eee262ecb43691db.jpg","images\\/0ec1530d5a80c860a403aa35be87d1ae.jpg"]',
                'retail_price' => '44.00',
                'sell_volume' => 12,
                'primary_product_id' => 0,
                'unit_price' => '44.00',
                'promotion_desc' => '泰国金枕榴莲火爆促销中，点我直达，萨瓦迪卡。',
                'promotion_tag' => 'sad',
                'vip_exclusive_price' => '11.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 1,
                'created_at' => '2018-06-16 02:14:38',
                'updated_at' => '2018-06-22 02:14:40',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 6,
                'goods_sn' => '',
                'goods_name' => '麻辣小龙虾1.5kg 4-6钱/25-32只',
                'brand_id' => 5,
                'goods_number' => 11,
                'keywords' => '海鲜年中大放价~满199立减50！',
                'goods_brief' => '海鲜年中大放价~满199立减50！',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/XIeXCjLIrHLmHcVjxpTeqEbXTLsnz1PwqfT6wznQ.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/hreEkhit0pYCO0PO5cFLjeQ6L6K2RraWyquz72H7.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/oFP0uFtAuZScfumtDZnbaVLgYofJQuNYcUZ3lliS.jpeg" style="max-width:100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/xy5I2z2QGHw8A6VKSEpdnqhD2EhBulSZFCxDdmpR.jpeg" style="max-width: 100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/JVZbnWtzLpl7X2LlIlVnFLIxwFGA88LQm7VEd9rF.jpeg" style="max-width: 100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/zz66BjTwqCSHzn91Tpwqkj1S9RGWeEeB1Ky3JdNn.jpeg" style="max-width:100%;"><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/lRtSV7YivDRLe5LhGVdqBmEJwHeB7sQaogwzOENX.jpeg" style="max-width: 100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '21.00',
                'freight_price' => '0.00',
                'extra_price' => '121.00',
                'is_new' => 0,
                'goods_unit' => '',
                'primary_pic_url' => 'images/815388791fef8d7deda3c98d0e084be5.jpg',
                'list_pic_url' => '["images\\/e485912f9d593995341cd5fd9f856efb.jpg","images\\/0f10a83c456f525507bb7c1478b70c23.jpg","images\\/acf43356e2506faedd12c8bdbe11ca2e.jpg"]',
                'retail_price' => '121.00',
                'sell_volume' => 0,
                'primary_product_id' => 0,
                'unit_price' => '343.00',
                'promotion_desc' => '海鲜年中大放价~满199立减50！',
                'promotion_tag' => '满199立减50',
                'vip_exclusive_price' => '213.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 1,
                'created_at' => '2018-06-16 02:41:00',
                'updated_at' => '2018-06-16 02:43:51',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 0,
                'goods_sn' => '',
                'goods_name' => '联想大连未来城项目',
                'brand_id' => 4,
                'goods_number' => 12,
                'keywords' => '大连未来城塑造全新官网',
                'goods_brief' => '采用“滚动视差”进行设计，多层背景以不同的速度移动，形成立体的运动效果，从不同的空间角度为用户带来非常惊艳的视觉体验',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/216574.jpg" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '20000.00',
                'freight_price' => '0.00',
                'extra_price' => '20000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/0f5b746b3e22b97431815864412db461.jpg',
                'list_pic_url' => '["images\\/5853d0e097916ed38672af1743f4669b.jpg"]',
                'retail_price' => '40000.00',
                'sell_volume' => 0,
                'primary_product_id' => 0,
                'unit_price' => '40000.00',
                'promotion_desc' => '暂无优惠',
                'promotion_tag' => '暂无优惠',
                'vip_exclusive_price' => '20000.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 0,
                'created_at' => '2018-06-23 03:58:30',
                'updated_at' => '2018-06-23 09:54:08',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 9,
                'goods_sn' => '',
                'goods_name' => '仿游戏平台',
                'brand_id' => 4,
                'goods_number' => 11,
                'keywords' => '仿游戏平台，让爱玩游戏的朋友通过做游戏任务获得相应利益。',
                'goods_brief' => '仿游戏平台，让爱玩游戏的朋友通过做游戏任务获得相应利益。',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/HGhj4jzWHvfRaTaFCSfgpumo08nJYrWla8RlIaCH.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/hTavziTNUeF48sUdIqMo97sufNS3FBkLp1afbL08.jpeg" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/LkKFb7QFFOgCJne2tlvmuMBQBehXM4T1HF32shrX.jpeg" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '20000.00',
                'freight_price' => '0.00',
                'extra_price' => '10000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/a58a626dfa884e7a078510c0a5bdd4d9.jpg',
                'list_pic_url' => '["images\\/d1a1a08014cc0e203fa6e2513f015b4f.jpg"]',
                'retail_price' => '30000.00',
                'sell_volume' => 0,
                'primary_product_id' => 0,
                'unit_price' => '30000.00',
                'promotion_desc' => '暂无优惠',
                'promotion_tag' => '暂无优惠',
                'vip_exclusive_price' => '0.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 0,
                'created_at' => '2018-06-23 05:14:21',
                'updated_at' => '2018-06-23 10:00:33',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 9,
                'goods_sn' => '',
                'goods_name' => '仿医疗APP',
                'brand_id' => 4,
                'goods_number' => 100,
                'keywords' => '医疗APP系统',
                'goods_brief' => '医疗APP系统',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/cIclvpPi7cCG6NZgyOOvmadbNbAtgr9HalrYXCuO.gif" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/1529748234822643093.jpg-_600" style="max-width:100%;"><br></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/1529748235778111900.jpg-_600" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '20000.00',
                'freight_price' => '0.00',
                'extra_price' => '10000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/e9d575f23f53ebb162ad2614ae3594a6.png',
                'list_pic_url' => '["images\\/b5c71efb6e8c2d351fb8999144455f9f.jpg"]',
                'retail_price' => '30000.00',
                'sell_volume' => 10,
                'primary_product_id' => 0,
                'unit_price' => '30000.00',
                'promotion_desc' => '暂无优惠',
                'promotion_tag' => '暂无优惠',
                'vip_exclusive_price' => '0.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 0,
                'created_at' => '2018-06-23 10:09:39',
                'updated_at' => '2018-06-23 10:12:33',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 3,
                'goods_sn' => '',
                'goods_name' => '旅游类项目1',
                'brand_id' => 4,
                'goods_number' => 10,
                'keywords' => '旅游类APP和微信小程序系统',
                'goods_brief' => '旅游类APP和微信小程序系统',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/1817016.jpg-_600" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '40000.00',
                'freight_price' => '0.00',
                'extra_price' => '10000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/104735724f1cf95d1aa019b5a8eb5751.png',
                'list_pic_url' => '["images\\/407d489d4ccf6ced57d6eacdf4e5fd2f.png"]',
                'retail_price' => '50000.00',
                'sell_volume' => 1,
                'primary_product_id' => 0,
                'unit_price' => '50000.00',
                'promotion_desc' => '暂无',
                'promotion_tag' => '暂无',
                'vip_exclusive_price' => '0.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 0,
                'created_at' => '2018-06-23 10:20:35',
                'updated_at' => '2018-06-23 10:20:35',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 3,
                'goods_sn' => '',
                'goods_name' => '旅游相关项目2',
                'brand_id' => 4,
                'goods_number' => 10,
                'keywords' => '旅游相关app和微信小程序系统',
                'goods_brief' => '旅游相关app和微信小程序系统',
                'goods_desc' => '<p></p><p><img src="https://xiaot-static.oss-cn-hangzhou.aliyuncs.com/XiaoT/763797.jpg-_600" style="max-width:100%;"><br></p>',
                'is_on_sale' => 1,
                'sort_order' => 255,
                'is_delete' => 0,
                'attribute_category' => 0,
                'counter_price' => '50000.00',
                'freight_price' => '0.00',
                'extra_price' => '10000.00',
                'is_new' => 1,
                'goods_unit' => '',
                'primary_pic_url' => 'images/82a32a00480f24425c3313373c24ab3a.png',
                'list_pic_url' => '["images\\/31968030c7065ddecdbb8cbce666f4e3.png","images\\/944ff15cbfdb436a8efeb7c92d655b53.png"]',
                'retail_price' => '60000.00',
                'sell_volume' => 0,
                'primary_product_id' => 0,
                'unit_price' => '60000.00',
                'promotion_desc' => '暂无',
                'promotion_tag' => '暂无',
                'vip_exclusive_price' => '0.00',
                'is_vip_exclusive' => 0,
                'is_limited' => 0,
                'is_hot' => 1,
                'created_at' => '2018-06-23 10:28:34',
                'updated_at' => '2018-06-23 10:28:34',
            ),
        ));
        
        
    }
}