<?php

use Illuminate\Database\Seeder;

class ShopOrderTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shop_order')->delete();
        
        \DB::table('shop_order')->insert(array (
            0 => 
            array (
                'id' => 6,
                'order_sn' => '191058291485698700001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 08:47:36',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 08:47:36',
                'updated_at' => '2018-06-21 08:47:36',
            ),
            1 => 
            array (
                'id' => 7,
                'order_sn' => '124058291487275500001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 08:47:52',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 08:47:52',
                'updated_at' => '2018-06-21 08:47:52',
            ),
            2 => 
            array (
                'id' => 8,
                'order_sn' => '159058291497453200001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 08:49:34',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 08:49:34',
                'updated_at' => '2018-06-21 08:49:34',
            ),
            3 => 
            array (
                'id' => 9,
                'order_sn' => '150058291504125900001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 08:50:41',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 08:50:41',
                'updated_at' => '2018-06-21 08:50:41',
            ),
            4 => 
            array (
                'id' => 21,
                'order_sn' => '188058291604682400001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 09:07:26',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 09:07:26',
                'updated_at' => '2018-06-21 09:07:26',
            ),
            5 => 
            array (
                'id' => 22,
                'order_sn' => '166058291886492600001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 09:54:24',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 09:54:24',
                'updated_at' => '2018-06-21 09:54:24',
            ),
            6 => 
            array (
                'id' => 23,
                'order_sn' => '122058291930124500001',
                'trade_no' => '',
                'uid' => 0,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '打卡发放山东矿机阿范德萨发卡仕达',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-21 10:01:41',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-21 10:01:41',
                'updated_at' => '2018-06-21 10:01:41',
            ),
            7 => 
            array (
                'id' => 24,
                'order_sn' => '119058297768038000301',
                'trade_no' => '',
                'uid' => 3,
                'order_status' => 10,
                'shipping_status' => 0,
                'pay_status' => 0,
                'consignee' => '史庆闯',
                'country' => 1,
                'province' => 2,
                'city' => 37,
                'district' => 407,
                'address' => '都发到撒多多撒大所',
                'mobile' => '13717674036',
                'postscript' => '用户无留言',
                'shipping_fee' => '0.00',
                'pay_name' => '微信支付',
                'pay_id' => 1,
                'actual_price' => '268.00',
                'integral' => 0,
                'integral_money' => '0.00',
                'order_price' => '268.00',
                'goods_price' => '268.00',
                'add_time' => '2018-06-22 02:14:40',
                'confirm_time' => '1970-01-01 08:00:01',
                'pay_time' => 0,
                'freight_price' => 0,
                'coupon_id' => 0,
                'parent_id' => 0,
                'coupon_price' => '0.00',
                'callback_status' => 0,
                'created_at' => '2018-06-22 02:14:40',
                'updated_at' => '2018-06-22 02:14:40',
            ),
        ));
        
        
    }
}