// Code generated by goctl. DO NOT EDIT.
package types

type FormPush struct {
	Msg      string `json:"msg" binding:"required"`
	ToUserId string `json:"toUserId" binding:"required"`
	RoomId   int    `json:"roomId" binding:"required"`
}

type PushResp struct {
	Code    uint32      `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type FormRoom struct {
	Msg    string `json:"msg" binding:"required"`
	RoomId int    `json:"roomId" binding:"required"`
}

type FormCount struct {
	RoomId int `json:"roomId" binding:"required"`
}

type FormRoomInfo struct {
	RoomId int `json:"roomId" binding:"required"`
}
