// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: logic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogicsClient is the client API for Logics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicsClient interface {
	//返送单条消息
	Push(ctx context.Context, in *Send, opts ...grpc.CallOption) (*LGSuccessReply, error)
}

type logicsClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicsClient(cc grpc.ClientConnInterface) LogicsClient {
	return &logicsClient{cc}
}

func (c *logicsClient) Push(ctx context.Context, in *Send, opts ...grpc.CallOption) (*LGSuccessReply, error) {
	out := new(LGSuccessReply)
	err := c.cc.Invoke(ctx, "/pb.logics/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicsServer is the server API for Logics service.
// All implementations must embed UnimplementedLogicsServer
// for forward compatibility
type LogicsServer interface {
	//返送单条消息
	Push(context.Context, *Send) (*LGSuccessReply, error)
	mustEmbedUnimplementedLogicsServer()
}

// UnimplementedLogicsServer must be embedded to have forward compatible implementations.
type UnimplementedLogicsServer struct {
}

func (UnimplementedLogicsServer) Push(context.Context, *Send) (*LGSuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedLogicsServer) mustEmbedUnimplementedLogicsServer() {}

// UnsafeLogicsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicsServer will
// result in compilation errors.
type UnsafeLogicsServer interface {
	mustEmbedUnimplementedLogicsServer()
}

func RegisterLogicsServer(s grpc.ServiceRegistrar, srv LogicsServer) {
	s.RegisterService(&Logics_ServiceDesc, srv)
}

func _Logics_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Send)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicsServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.logics/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicsServer).Push(ctx, req.(*Send))
	}
	return interceptor(ctx, in, info, handler)
}

// Logics_ServiceDesc is the grpc.ServiceDesc for Logics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.logics",
	HandlerType: (*LogicsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Logics_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.proto",
}
