// Code generated by goctl. DO NOT EDIT!

package groups

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{})
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	groupsRowsWithPlaceHolder = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groups struct {
		Id          int64     `db:"id"`
		UserId      int64     `db:"user_id"`
		Title       string    `db:"title"`
		Description string    `db:"description"`
		ChannelId   string    `db:"channel_id"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newGroupsModel(conn sqlx.SqlConn) *defaultGroupsModel {
	return &defaultGroupsModel{
		conn:  conn,
		table: "`groups`",
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, groupsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.ChannelId)
	return ret, err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id int64) (*Groups, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
	var resp Groups
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Update(ctx context.Context, data *Groups) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.ChannelId, data.Id)
	return err
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
