// Code generated by goctl. DO NOT EDIT!
// Source: systemuserget.proto

package server

import (
	"context"

	"backend/service/backend/cmd/rpc/systemuserget/internal/logic"
	"backend/service/backend/cmd/rpc/systemuserget/internal/svc"
	"backend/service/backend/cmd/rpc/systemuserget/systemuserget"
)

type SystemusergeterServer struct {
	svcCtx *svc.ServiceContext
}

func NewSystemusergeterServer(svcCtx *svc.ServiceContext) *SystemusergeterServer {
	return &SystemusergeterServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemusergeterServer) GetSystemuser(ctx context.Context, in *systemuserget.Request) (*systemuserget.Response, error) {
	l := logic.NewGetSystemuserLogic(ctx, s.svcCtx)
	return l.GetSystemuser(in)
}
