export default [{
	"image": "/static/gift/1.png",
	"id": 1,
	"name": "鸡蛋",
	"coin": 1
}, {
	"image": "/static/gift/2.png",
	"id": 2,
	"name": "666",
	"coin": 2
}, {
	"image": "/static/gift/3.png",
	"id": 3,
	"name": "雪糕",
	"coin": 3
}, {
	"image": "/static/gift/4.png",
	"id": 4,
	"name": "龙虾",
	"coin": 4
}, {
	"image": "/static/gift/5.png",
	"id": 5,
	"name": "精灵球",
	"coin": 5
}, {
	"image": "/static/gift/6.png",
	"id": 6,
	"name": "胶囊",
	"coin": 6
}, {
	"image": "/static/gift/7.png",
	"id": 7,
	"name": "爱心",
	"coin": 7
}, {
	"image": "/static/gift/8.png",
	"id": 8,
	"name": "花",
	"coin": 8
}]
